spring:
  data:
    elasticsearch:
      repositories:
      #开启 Elasticsearch 仓库(默认值:true)
        enabled: true
      # elasticsearch节点
      cluster-nodes: 192.168.70.80:9300
      # 集群名称
      cluster-name: elasticsearch
      properties:
        path:
        # 索引的存储位置
          home: /root/soft/elasticsearch-7.0.0/data/nodes
        transport:
          tcp:
          # 连接超时时间
            connect_timeout: 120s